# Generated by Django 5.0.9 on 2024-11-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0625_merge_20241117_1821"),
        ("zerver", "0629_remove_stream_email_token_backfill_channelemailaddress"),
    ]

    operations = []
